version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "8912:8912"
    env_file: .env
    command: >
      bash -c "dockerize -wait tcp://db:5432 -timeout 90s yarn knex migrate:latest && yarn start"
  db:
    image: "postgres"
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    restart: always
